version: 0.9.3-beta-{build}
os: Visual Studio 2015
clone_depth: 10
clone_folder: C:\projects\CacheManager\
install:
- C:\projects\CacheManager\tools\redis\install-service.cmd
before_build:
- nuget restore C:\projects\cachemanager\CacheManager.Msbuild.sln
build:
  project: C:\projects\cachemanager\CacheManager.Msbuild.sln
  verbosity: minimal
test:
  categories:
    except:
    - Memcached
    - Unreliable